# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project info
site_name: Hummingbot
site_description: The official Hummingbot website and documentation
site_author: Hummingbot Foundation
site_url: https://hummingbot.org

# Repository
repo_name: 'hummingbot/hummingbot'
repo_url: 'https://github.com/hummingbot/hummingbot'
edit_uri: 'https://github.com/hummingbot/hummingbot-site/blob/master/'

# Copyright
copyright: Copyright &copy; 2023 Hummingbot Foundation

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/brand/favicon.svg
  favicon: assets/brand/logo-color.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
  font:
      text: Noto Sans
      code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.code.copy
    - toc.follow
    # - content.tabs.link
    # - content.tooltips
    # - search.highlight

plugins:
  - social:
      cards_layout_options:
        background_color: "#151819"
        color: "#5FFFD7"
  - search
  - mkdocs-video
  - blog
  # - git-revision-date

extra:
  homepage: https://hummingbot.org
  generator: true
  analytics:
    provider: google
    property: UA-119262087-3
    feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >- 
                Thanks for your feedback! Help us improve this page by
                <a href="https://github.com/hummingbot/hummingbot-site/issues/new?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">filing an issue</a>.
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hummingbot
    - icon: fontawesome/brands/github
      link: https://github.com/hummingbot/hummingbot
    - icon: fontawesome/brands/youtube
      link: https://youtube/c/hummingbot
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_hummingbot
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hummingbot-foundation

extra_css:
  - assets/css/custom.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  # - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     user: hummingbot
  #     repo: hummingbot
  #     repo_url_shorthand: true
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - tables

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Getting Started: installation/index.md
    - Install via Docker: installation/docker.md
    - Install from Source: 
      - Install from Source: installation/source/index.md
      - Linux: installation/linux.md
      - MacOS: installation/mac.md
      - Windows: installation/windows.md        
      - Raspberry Pi: installation/raspberry-pi.md
    - Post-Installation: installation/post-installation.md
    - Quickstart:
      - Quickstart: quickstart/index.md
      - Exercise 1 - Hello World: quickstart/custom-pmm-1.md
      - Exercise 2 - Simple PMM: quickstart/custom-pmm-2.md
      - Exercise 3 - Customize Status: quickstart/custom-pmm-3.md
      - Exercise 4 - Basic Price Ceiling/Floor: quickstart/custom-pmm-4.md
      - Exercise 5 - Dynamic Price Ceiling/Floor: quickstart/custom-pmm-5.md
    - Glossary: glossary.md
    - Troubleshooting: troubleshooting.md
  - Docs:
    - Docs: docs/index.md
    - Client Interface:
      - Client: operation/index.md
      - User Interface Guide: operation/user-interface.md
      - Commands and Shortcuts: operation/commands-shortcuts.md
      - Launch/Exit Hummingbot: operation/launch-exit.md
      - Create/Delete Password: operation/password.md
      - Connect Exchange API Keys: operation/connect.md
      - Create/Import Config Files: operation/config-files.md
      - Check Balances: operation/balance.md
      - Start/Stop Strategy: operation/start-stop.md
      - Check Bot/Market Status: operation/status.md
      - Check Performance: operation/history.md
      - Find Log Files: operation/log-files.md
      - Export Trades/Keys: operation/export.md
    - Client Utilities:
      - Paper Trade: global-configs/paper-trade.md
      - Balance Limit: global-configs/balance-limit.md
      - Kill Switch: global-configs/kill-switch.md
      - Rate Oracle: strategy-configs/rate-oracle.md
      - Rate Limits Share Pct: global-configs/rate-limits-share-pct.md
      - Telegram Integration: global-configs/telegram.md
      - Data Collector: global-configs/data-collector.md
      - Auto-start from Command Line: global-configs/strategy-autostart.md
    - Customizing the Client:
      - Override Fees: global-configs/override-fees.md
      - Clock Tick Size: global-configs/clock-tick.md 
      - Color Settings: global-configs/color-settings.md
      - Connect External Database: global-configs/external-db.md
      - Debug Console: developers/debug.md
      - Adding Commands: developers/commands.md
    - Scripts and Smart Components:
      - Scripts: scripts/index.md
      - Cheatsheat: scripts/cheatsheet.md
      - Sample Scripts: scripts/examples.md
      - Candles Feed: scripts/candles-feed.md
      - Smart Components: scripts/smart-components.md
    - Strategies:
      - Strategies: strategies/index.md
      - Pure Market Making: strategies/pure-market-making.md
      - Cross-Exchange Market Making: strategies/cross-exchange-market-making.md
      - AMM Arbitrage: strategies/amm-arbitrage.md
      - Avellaneda Market Making: strategies/avellaneda-market-making.md
      - Cross-Exchange Mining: strategies/cross-exchange-mining.md
      - Hedge: strategies/hedge.md
      - Liquidity Mining: strategies/liquidity-mining.md
      - Perpetual Market Making: strategies/perpetual-market-making.md
      - Spot Perpetual Arbitrage: strategies/spot-perpetual-arbitrage.md
      - TWAP: strategies/twap.md
      - Uniswap v3 LP: strategies/uniswap-v3-lp.md
      - Building Strategies:
        - Building Strategies: developers/strategies/index.md
        - Architecture: developers/strategies/architecture.md
        - Tutorial: developers/strategies/tutorial.md
        - Key Concepts: developers/strategies/key-concepts.md
        - Define Configs: developers/strategies/config.md
        - Hanging Orders Tracker: developers/strategies/hanging-orders.md
      - PMM Configs:
        - PMM Configs: strategy-configs/index.md
        - Add Transaction Costs: strategy-configs/add-transaction-costs.md
        - Order Levels: strategy-configs/order-levels.md
        - Filled Order Delay: strategy-configs/filled-order-delay.md
        - Hanging Orders: strategy-configs/hanging-orders.md
        - Minimum Spread: strategy-configs/minimum-spread.md
        - Order Refresh Tolerance: strategy-configs/order-refresh-tolerance.md
        - Order Optimization: strategy-configs/order-optimization.md
        - Inventory Skew: strategy-configs/inventory-skew.md
        - Max Order Age: strategy-configs/max-order-age.md
        - Order Override: strategy-configs/order-override.md
        - Price Band: strategy-configs/price-band.md
        - Price Source: strategy-configs/external-price-source.md
        - Ping Pong: strategy-configs/ping-pong.md
      - PMM Scripts: scripts/pmm-scripts.md
    - Connectors:
      - Connectors: exchanges/index.md
      - CEX Connectors:
        - Binance 🥇: exchanges/binance/index.md
        - Kucoin 🥈: exchanges/kucoin/index.md
        - Gate.io 🥈: exchanges/gate-io/index.md
        - AscendEX 🥈: exchanges/ascendex/index.md
        - AltMarkets: exchanges/altmarkets.md
        - Binance US: exchanges/binance-us/index.md
        - Bybit: exchanges/bybit.md
        - Bitfinex: exchanges/bitfinex.md
        - BitGet: exchanges/bitget-perpetual.md
        - BitMart: exchanges/bitmart/index.md
        - Bitmex: exchanges/bitmex.md
        - Bittrex: exchanges/bittrex.md
        - BTC Markets: exchanges/btc-markets.md
        - Coinbase: exchanges/coinbase.md
        - HitBTC: exchanges/hitbtc.md
        - Hotbit: exchanges/hotbit.md
        - Huobi: exchanges/huobi/index.md
        - Kraken: exchanges/kraken/index.md
        - MEXC: exchanges/mexc/index.md
        - NDAX: exchanges/ndax.md
        - OKX: exchanges/okx.md
        - Phemex: exchanges/phemex-perpetual.md
      - DEX Connectors:
        - Uniswap 🥇: exchanges/uniswap.md
        - dYdX 🥈: exchanges/dydx.md
        - Pancakeswap 🥈: exchanges/pancakeswap.md
        - Dexalot 🥈: exchanges/dexalot.md
        - Defira: exchanges/defira.md
        - Injective: exchanges/injective.md
        - Loopring: exchanges/loopring/index.md
        - Mad Meerkat: exchanges/mad-meerkat.md
        - OpenOcean: exchanges/openocean.md
        - Pangolin: exchanges/pangolin.md
        - Perpetual Protocol: exchanges/perp.md
        - Polkadex: exchanges/polkadex.md
        - Quickswap: exchanges/quickswap.md
        - Ref: exchanges/ref.md
        - Sushiswap: exchanges/sushiswap.md
        - Tinyman: exchanges/tinyman.md
        - TraderJoe: exchanges/traderjoe.md
        - Vertex: exchanges/vertex.md
        - VVS: exchanges/vvs.md
        - XSwap: exchanges/xswap.md
      - Chain Connectors:
        - Chains: chains/index.md
        - Ethereum: chains/ethereum.md
        - Avalanche: chains/avalanche.md
        - Algorand: chains/algorand.md
        - BNB Chain: chains/bnb-chain.md
        - Cronos: chains/cronos.md
        - Cosmos: chains/cosmos.md
        - Harmony: chains/harmony.md
        - Injective: chains/injective.md
        - NEAR: chains/near.md
        - Polygon: chains/polygon.md
        - XDC Chain: chains/xdc-chain.md
      - Building CEX Connectors:
        - Building CEX Connectors: developers/connectors/index.md
        - Architecture: developers/connectors/architecture/index.md
        - Order Lifecycle and Market Events: developers/connectors/architecture/order_lifecycle.md
        - API Throttler: developers/connectors/architecture/api_throttler.md
        - Build Process: developers/connectors/build.md
        - QA Testing Process: developers/connectors/test.md
        - Debugging: developers/connectors/debug.md
      - Building DEX Connectors: gateway/adding-dex-connectors.md
    - Gateway:
      - Gateway: gateway/index.md
      - Installation: gateway/installation.md
      - Testing Gateway: gateway/testing.md
      - Using Gateway with Hummingbot: gateway/setup.md
      - Working with Tokens: gateway/tokens.md
      - Running DEX Bots: gateway/running-dex-bots.md
      - API Reference: gateway/api-reference.md
    - Broker Module: installation/orchestration.md
  - Releases:
    - Releases: release-notes/index.md
    - Release Process: governance/releases.md
    - 1.18.0: release-notes/1.18.0.md
    - 1.17.0: release-notes/1.17.0.md
    - 1.16.0: release-notes/1.16.0.md
    - 1.15.0: release-notes/1.15.0.md
    - 1.14.0: release-notes/1.14.0.md
    - 1.13.0: release-notes/1.13.0.md 
    - 1.12.0: release-notes/1.12.0.md
    - 1.11.0: release-notes/1.11.0.md
    - 1.10.0: release-notes/1.10.0.md
    - 1.9.0: release-notes/1.9.0.md
    - 1.8.0: release-notes/1.8.0.md
    - 1.7.0: release-notes/1.7.0.md
    - 1.6.0: release-notes/1.6.0.md
    - 1.5.0: release-notes/1.5.0.md
    - 1.4.0: release-notes/1.4.0.md
    - 1.3.0: release-notes/1.3.0.md
    - 1.2.0: release-notes/1.2.0.md
    - 1.1.1: release-notes/1.1.1.md
    - 1.1.0: release-notes/1.1.0.md
    - 1.0.1: release-notes/1.0.1.md
    - 1.0.0: release-notes/1.0.0.md
  - Community:
    - Community: community/index.md
    - Events: community/events.md
    - Botcamp: community/botcamp.md 
    - Bounties: 
      - Bounties: bounties/index.md
      - For Contributors: bounties/contributors.md
      - For Sponsors: bounties/sponsors.md
      - Bounties Board ↗️: https://github.com/orgs/hummingbot/projects/7/views/1
    - Governance: 
      - Governance: governance/index.md
      - Epochs: governance/epochs.md
      - Polls: governance/polls.md
      - Proposals: governance/proposals.md
      - Whitepaper: governance/whitepaper.md
    - Contribution Guidelines: developers/contributions.md
    - Forking the Repository: developers/forking.md
    - 📆 Calendar ↗️: https://hummingbot-foundation.notion.site/5c767683f80b45c4934aa8cf755a2ff5?v=4dd057ac162f49c9813e11cec0688204
  - About:
    - About: about/index.md
    - FAQ: faq.md
    - Board of Directors: governance/board.md
    - Reporting: reporting.md
    - History: about/history.md
    - ❤️ Support Us: support-hummingbot.md
  - Blog: 
    - blog/index.md
