[build]
    command = "pip install git+https://github.com/hummingbot/mkdocs-material-insiders.git mkdocs-git-revision-date-plugin pillow cairosvg p && mkdocs build"
    publish = "site"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".cache"]