foundation:
  name: Hummingbot
  description: Foundation
  avatar: /assets/brand/logo-color.png
  
carlo:
  name: Carlo Las Marias
  description: CEO, CoinAlpha
  avatar: /assets/authors/carlo-las-marias.jpg

mike:
  name: Michael Feng
  description: COO, Hummingbot Foundation
  avatar: /assets/authors/michael-feng.jpg

martin:
  name: Martin Kou
  description: CTO, CoinAlpha
  avatar: /assets/authors/martin-kou.jpg
fede:
  name: Fede Cardoso
  description: CTO, Hummingbot Foundation
  avatar: /assets/authors/fede-cardoso.jpg
